((section . platform) (name . github) (api-base . "https://api.github.com") (auth-env . "GITHUB_TOKEN") (auth-fallback . "gh auth token"))
((section . platform) (name . gitcode) (api-base . "https://api.gitcode.com") (auth-env . "GITCODE_TOKEN") (auth-fallback . #f))
((section . rule) (id . "no-sql-injection") (description . "Flag SQL string concatenation or interpolation") (severity . critical) (category . security))
((section . rule) (id . "no-hardcoded-secrets") (description . "Flag hardcoded passwords, API keys, or tokens") (severity . critical) (category . security))
((section . rule) (id . "error-handling") (description . "Flag ignored errors or bare unwrap in production code") (severity . warning) (category . correctness))
((section . rule) (id . "no-unbounded-alloc") (description . "Flag unbounded Vec/HashMap growth from user input") (severity . warning) (category . performance))
((section . settings) (default-mode . auto) (max-inline-comments . 20))
